import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/app/navigation";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="p-8">
                <Navigation />
                <main>{children}</main>
            </body>
        </html>
    );
}
